<?php
const BASE_URL = 'https://gildas-le-drogoff.alwaysdata.net/academie/';
const PUBLIC_URL = 'https://gildas-le-drogoff.alwaysdata.net/academie/public/';
const ROOT = __DIR__ . DIRECTORY_SEPARATOR;
const PUBLIC_ROOT = ROOT . 'public' . DIRECTORY_SEPARATOR;
const VIEWS_ROOT = ROOT . 'app' . DIRECTORY_SEPARATOR . 'Views' . DIRECTORY_SEPARATOR;
const MODELS_ROOT = ROOT . 'app' . DIRECTORY_SEPARATOR . 'Models' . DIRECTORY_SEPARATOR;
const CONTROLLERS_ROOT = ROOT . 'app' . DIRECTORY_SEPARATOR . 'Controllers' . DIRECTORY_SEPARATOR;
const CONFIG_ROOT = ROOT . 'config' . DIRECTORY_SEPARATOR;
const FAVICON_ROOT = PUBLIC_ROOT . 'favicon' . DIRECTORY_SEPARATOR;
const CSS_ROOT = PUBLIC_ROOT . 'css' . DIRECTORY_SEPARATOR;
const JS_ROOT = PUBLIC_ROOT . 'js' . DIRECTORY_SEPARATOR;
const IMG_ROOT = PUBLIC_ROOT . 'img' . DIRECTORY_SEPARATOR;
const FONT_ROOT = PUBLIC_ROOT . 'font' . DIRECTORY_SEPARATOR;
const FAVICON_URL = PUBLIC_URL . 'favicon/';
const CSS_URL = PUBLIC_URL . 'css/';
const JS_URL = PUBLIC_URL . 'js/';
const IMG_URL = PUBLIC_URL . 'img/';
const FONT_URL = PUBLIC_URL . 'font/';
const FAVICON_PATH = FAVICON_ROOT . 'favicon.php';
const CSS_PATH = CSS_ROOT . 'fix.css';
const JS_PATH = JS_ROOT . 'fix.js';
const IMG_PATH = IMG_ROOT . 'fix.png';
const FONT_PATH = FONT_ROOT . 'fix.ttf';
const FAVICON_CONTENT = '<link rel="icon" href="' . FAVICON_URL . 'favicon.php" />';
const CSS_CONTENT = '<link rel="stylesheet" href="' . CSS_URL . 'fix.css" />';
const JS_CONTENT = '<script src="' . JS_URL . 'fix.js"></script>';
const IMG_CONTENT = '<img src="' . IMG_URL . 'fix.png" />';
const FONT_CONTENT = '<link href="' . FONT_URL . 'fix.ttf" rel="stylesheet" type="text/css" />';
const FAVICON_CONTENT_FAIL = '<link rel="icon" href="' . FAVICON_URL . 'favicon.php" />';
const CSS_CONTENT_FAIL = '<link rel="stylesheet" href="' . CSS_URL . 'fix.css" />';
const JS_CONTENT_FAIL = '<script src="' . JS_URL . 'fix.js"></script>';
const IMG_CONTENT_FAIL = '<img src="' . IMG_URL . 'fix.png" />';
const FONT_CONTENT_FAIL = '<link href="' . FONT_URL . 'fix.ttf" rel="stylesheet" type="text/css" />';
